# Generated by Django 3.1.2 on 2020-10-23 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 10, 23, 17, 7, 31, 84846, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
