# Generated by Django 3.1.2 on 2020-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_userlogin_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
